
addons:
  apt:
    packages:
    - aria2
#before_install:
branches:
  only:
  - develop
  - master

dist: trusty
env:
  global:
  - IMAGE_ARG_APT_MIRROR=archive.ubuntu.com
  matrix:
  - IMAGE_ARG_RUBY_VERSION=2.6.1
  - IMAGE_ARG_RUBY_VERSION=2.5.3

group: edge
#install: true

#before_script:
script:
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- bash build.sh
- kill %1
#after_script:

services:
- docker
sudo: required
